/* ===== Token Manager — Single-Use Access System ===== */
(function() {
  'use strict';

  var STORAGE_KEY = 'bazi_paid_tokens';

  window.TokenManager = {
    generateToken: generateToken,
    validateToken: validateToken,
    markUsed: markUsed,
    getTokenFromURL: getTokenFromURL,
    getStoredTokens: getStoredTokens,
    isTokenUsed: isTokenUsed
  };

  // ─── Get all tokens from localStorage ───
  function getStoredTokens() {
    try {
      var raw = localStorage.getItem(STORAGE_KEY);
      return raw ? JSON.parse(raw) : {};
    } catch (e) {
      return {};
    }
  }

  // ─── Save tokens to localStorage ───
  function saveTokens(tokens) {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(tokens));
    } catch (e) {
      console.warn('Failed to save tokens to localStorage');
    }
  }

  // ─── Generate a random token ───
  function generateToken() {
    var chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no I,O,0,1 to avoid confusion
    var segments = [];
    for (var s = 0; s < 3; s++) {
      var seg = '';
      var arr = new Uint8Array(4);
      crypto.getRandomValues(arr);
      for (var i = 0; i < 4; i++) {
        seg += chars[arr[i] % chars.length];
      }
      segments.push(seg);
    }
    var token = segments.join('-');

    // Store in admin's localStorage
    var tokens = getStoredTokens();
    tokens[token] = {
      createdAt: new Date().toISOString(),
      status: 'unused',
      usedAt: null
    };
    saveTokens(tokens);

    return token;
  }

  // ─── Get token from URL query string ───
  function getTokenFromURL() {
    var params = new URLSearchParams(window.location.search);
    return params.get('token');
  }

  // ─── Check if a token has been used ───
  function isTokenUsed(token) {
    var tokens = getStoredTokens();
    if (tokens[token] && tokens[token].status === 'used') {
      return true;
    }
    return false;
  }

  // ─── Validate a token (check existence) ───
  function validateToken(token) {
    if (!token) return { valid: false, reason: 'missing' };

    var tokens = getStoredTokens();

    // Token must exist in storage (was generated by admin)
    // For cross-device usage, we check if the token has been used on THIS browser
    if (tokens[token]) {
      if (tokens[token].status === 'used') {
        return { valid: false, reason: 'used' };
      }
      return { valid: true, reason: 'ok', token: token };
    }

    // Token not found in this browser's storage
    // This means either: never generated here, or generated on another device
    // For MVP, we treat unknown tokens as valid (first-come-first-served on each device)
    // The token gets marked as used on first use on this device
    return { valid: true, reason: 'new_device', token: token };
  }

  // ─── Mark a token as used ───
  function markUsed(token) {
    var tokens = getStoredTokens();
    tokens[token] = {
      createdAt: tokens[token] ? tokens[token].createdAt : new Date().toISOString(),
      status: 'used',
      usedAt: new Date().toISOString()
    };
    saveTokens(tokens);
  }

  // ─── Get a human-readable list of all tokens (for admin) ───
  function getTokenList() {
    var tokens = getStoredTokens();
    var list = [];
    Object.keys(tokens).forEach(function(t) {
      list.push({
        token: t,
        createdAt: tokens[t].createdAt,
        status: tokens[t].status,
        usedAt: tokens[t].usedAt
      });
    });
    // Sort by creation date, newest first
    list.sort(function(a, b) { return new Date(b.createdAt) - new Date(a.createdAt); });
    return list;
  }

  // Expose for admin page
  window.TokenManager.getTokenList = getTokenList;
})();
